### PR TITLE
Allow (listen to/play) before Skip and Previous.

### PR DESCRIPTION
**Pull request by jingai**
And 'play' before ListenToArtist.  I haven't noticed any issues with it and find myself accidentally saying 'play' a lot for music.

### CODE REVIEW

**Comment by jingai** [comment]
Rebased.

**Comment by jingai** [comment]
Do you want me to break this up?  Admittedly, it started as its namesake and then grew a tad.

**Comment by m0ngr31** [comment]
Yeah, if you think it'll help

**Comment by jingai** [comment]
Better?

Quick question though:  did you mean for the default port in kodi.py to be 8089 instead of 8080?

**Comment by m0ngr31** [comment]
It's just what mine is set to, so it's easier to debug for me to leave it on 8089.

**Comment by jingai** [comment]
Oh, ok no problem.  I just thought you fumble-fingered it :)

**Comment by jingai** [comment]
Rebased.  Let me know if you have any issues with these additions.

**Comment by jingai** [comment]
This is pretty trivial and I haven't seen any issues with it, so I hope I'm not overstepping my bounds by merging it..

**Pull request merged**
