### PR TITLE
Add better support for music videos

### PR DESCRIPTION
**Pull request by jingai**
Allow the user to play/shuffle music videos like the other media types.  Support has been added for shuffling music videos, shuffling music videos by genre, and playing specific music videos.

Allowing the user to request music videos by a specific artist presented a little more difficulty, so I raised Issue #212 for that.

The new slot `MUSICVIDEOS` was required to implement this, which has already been added to the web slot generator and is included in the Python generator in this PR.

Requires changes to Kodi-Voice found in version 0.9.7.

_Needs German translations_

Addresses Issue #118.

### CODE REVIEW

**Comment by jingai** [comment]
Hmm.. it seems there is no VideoLibrary.GetMusicVideoArtists, so we might have to just use AudioLibrary.GetArtists for the match.. the only problem with that is that a user can have music videos but no/few music artists, which means we might not match artist due to too few samples.

I'm in favor of just going with AudioLibrary.GetArtists and re-using the `MUSICARTISTS` slot for this, personally.  But if anyone has a better suggestion, please speak up.

**Comment by jingai** [comment]
Ping @mcl22 and @ausweider for German translations :)

**Comment by mcl22** [comment]
Here you are:

could_not_find_musicvideo: "Konnte kein Musikvideo mit dem Namen {{ heard_musicvideo }} finden"
playing_musicvideo_card: "Spiele Musikvideo"
shuffling_musicvideos: "Spiele zufällige Musikvideos"
shuffling_musicvideos_genre: "Spiele zufällige {{ genre }} Musikvideos"
 
WatchMusicVideo zeige (/das) Musikvideo {MusicVideo}
ShuffleMusicVideos zeige (/zufällige/alle) (/{MusicVideoGenre}) Musikvideos

**Comment by jingai** [comment]
Thanks again @mcl22!

**Pull request merged**
