### PR TITLE
Extend genre support

### PR DESCRIPTION
**Pull request by jingai**
This PR tries to extend genre support everywhere applicable.  Previously, we supported specifying a genre only in WatchRandomMovie.  This extends it to the existing View Intents and creates the following new Intents:

```
ViewMusicVideos
WatchRandomShow
WatchRandomMusicVideo
```

Two new slots were required for this:

```
SHOWGENRES
MUSICVIDEOGENRES
```

These have been added to web slot generator already and the Python generator is updated in this PR.

Additionally, this requires already-released changes to Kodi-Voice in 0.9.6.

### CODE REVIEW

**Comment by mcl22** [comment]
Here are the translations:

playing_genre_musicvideo: "Spiele das {{ genre_name }} Musikvideo {{ musicvideo_name }} von {{ artist_name }}"
playing_musicvideo: "Spiele das Musikvideo {{ musicvideo_name }} von {{ artist_name }}"
playing_random_show: "Spiele eine zufällige Serie"
playing_random_show_genre: "Spiele eine zufällige {{ genre }} Serie"
playing_random_musicvideo: "Spiele ein zufälliges Musikvideo"
playing_random_musicvideo_genre: "Spiele ein zufälliges {{ genre }} Musikvideo"
 
WatchRandomShow zeige eine (/zufällige) (/{ShowGenre}) Serie
WatchRandomMusicVideo zeige ein (/zufälliges) (/{MusicVideoGenre}) Musikvideo
 
ViewMovies (suche/finde) {MovieGenre} Filme
ViewMovies suche nach {MovieGenre} Filmen
ViewShows (suche/suche nach/finde) {ShowGenre} Serien
ViewMusic (suche/suche nach/finde) {MusicGenre} Musik
ViewMusicVideos (suche/suche nach/finde) {MusicVideoGenre} Musikvideos

**Comment by jingai** [comment]
Thanks @mcl22.  But I don't think these are right:

> ViewMovies (suche/finde) {MovieGenre} Filme
> ViewMovies suche nach {MovieGenre} Filmen
> ViewShows (suche/suche nach/finde) {ShowGenre} Serien
> ViewMusic (suche/suche nach/finde) {MusicGenre} Musik
> ViewMusicVideos (suche/suche nach/finde) {MusicVideoGenre} Musikvideos

The English phrases are:

```
ViewMovies (open/go to/show) movies
ViewMovies (show/find/search for) {MovieGenre} movies
ViewShows (open/go to/show) (/t. v.) shows
ViewShows (show/find/search for) {ShowGenre} (/t. v.) shows
ViewMusic (open/go to/show) music
ViewMusic (show/find/search for) {MusicGenre} music
ViewArtists (open/go to/show) (artists/music artists/musicians)
ViewAlbums (open/go to/show) (/music) albums
```

Note the difference between `open/go to/show` and `show/find/search for`.  If a genre isn't specified, the user is essentially telling Kodi to "show, on-screen, the library view for that media type."  If a genre is specified, it's saying, "search for items of this genre and show them on-screen."

From what I can tell for German, we use `öffne/gehe zu` as the equivalent for `open/go to/show` and `suche/suche nach/find` as the equivalent for `show/find/search for`.

**Comment by jingai** [comment]
Thanks @mcl22.  Could you verify that all of these are now correct?  Thanks!

```
ViewMovies (öffne/gehe zu) Filme
ViewMovies (suche/finde) {MovieGenre} Filme
ViewMovies suche nach {MovieGenre} Filmen
ViewShows (öffne/gehe zu) Serien
ViewShows (suche/suche nach/finde) {ShowGenre} Serien
ViewMusic (öffne/gehe zu) Musik
ViewMusic (suche/suche nach/finde) {MusicGenre} Musik
ViewArtists (öffne/gehe zu) (Künstler/Musiker/Interpreten)
ViewAlbums (öffne/gehe zu) Alben
ViewMusicVideos (öffne/gehe zu) Musikvideos
ViewMusicVideos (suche/suche nach/finde) {MusicVideoGenre} Musikvideos
ViewAudioPlaylist (öffne/gehe zu) (Musik/Lieder/Song) playlist {AudioPlaylist}
ViewAudioPlaylist (öffne/gehe zu) {AudioPlaylist} (Musik/Lieder/Song) playlist
ViewAudioPlaylistRecent (öffne/gehe zu) neue (Musik/Lieder/Songs)
ViewAudioPlaylistRecent (öffne/gehe zu) (zuletzt/kürzlich) hinzugefügte (Musik/Lieder/Songs)
ViewVideoPlaylist (öffne/gehe zu) (Film/Serie/Video) playlist {VideoPlaylist}
ViewVideoPlaylist (öffne/gehe zu) {VideoPlaylist} (Film/Serie/Video) playlist
ViewMoviePlaylistRecent (öffne/gehe zu) neue (Films/Videos)
ViewMoviePlaylistRecent (öffne/gehe zu) (zuletzt/kürzlich) hinzugefügte (Films/Videos)
ViewEpisodePlaylistRecent (öffne/gehe zu) neue Series
ViewEpisodePlaylistRecent (öffne/gehe zu) (zuletzt/kürzlich) hinzugefügte Series
ViewEpisodePlaylistRecent (öffne/gehe zu) neue Musikvideos
ViewEpisodePlaylistRecent (öffne/gehe zu) (zuletzt/kürzlich) hinzugefügte Musikvideos
ViewPlaylist (öffne/gehe zu) playlist {AudioPlaylist}
ViewPlaylist (öffne/gehe zu) {AudioPlaylist} playlist
ViewPlaylist (öffne/gehe zu) playlist {VideoPlaylist}
ViewPlaylist (öffne/gehe zu) {VideoPlaylist} playlist
```

**Comment by mcl22** [comment]
Wow, this one is pretty difficult :)
First, here are my changes:
ViewVideoPlaylist (öffne/gehe zu) (Film/Serie/Video) playlist {VideoPlaylist}
ViewVideoPlaylist (öffne/gehe zu) (Filme/Serien) playlist {VideoPlaylist}
ViewMoviePlaylistRecent (öffne/gehe zu) neue (Filme/Videos)
ViewMoviePlaylistRecent (öffne/gehe zu) (zuletzt/kürzlich) hinzugefügte (Filme/Videos)
ViewEpisodePlaylistRecent (öffne/gehe zu) neue Serien
ViewEpisodePlaylistRecent (öffne/gehe zu) (zuletzt/kürzlich) hinzugefügten Serien

There are some more one could change but it's not so easy. For instance,
ViewAudioPlaylistRecent (öffne/gehe zu) (zuletzt/kürzlich) hinzugefügte (Musik/Lieder/Songs)
One could say "gehe zu kürzlich hinzugefügteR Musik" but you could also say "... hinzugefügte Musik" if you treat "kürzlich hinzugefügte Musik" as an "item", something static, for example a menu entry. Then you go to this entry and refer to that. But if you'd like to refer to the recently added music it would be "kürzlich hinzugefügter Musik".
With those corrections above I tried to match it to something I would use, don't know about others :) I could translate every possible version (as Amazon suggests) but then once again we would blow up the utterances :)
So, let's try it this way.

**Comment by jingai** [comment]
> ViewVideoPlaylist (öffne/gehe zu) (Film/Serie/Video) playlist {VideoPlaylist}
> ViewVideoPlaylist (öffne/gehe zu) (Filme/Serien) playlist {VideoPlaylist}

Are you trying to say that this isn't corect as an alternate:

`(öffne/gehe zu) {VideoPlaylist} (Film/Filme/Serie/Serien/Video) playlist`

?

Note the orientation of the word `playlist`

**Comment by jingai** [comment]
Going to merge this as it is for now.  There's a few other instances of these words that might need adjustments too, so let's treat that as its own Issue.

I _think_ Alexa might catch things like `film` vs `filme` and `serie` vs `serien` on her own anyway.  Let me know if that's the case.

**Comment by mcl22** [comment]
Concerning (öffne/gehe zu) {VideoPlaylist} (Film/Filme/Serie/Serien/Video) playlist, that was my fault :) Of course this works.

**Pull request merged**
