### PR TITLE
Add CurrentPlayItemInquiry Intent.

### PR DESCRIPTION
**Pull request by jingai**
Has Alexa speak the currently playing movie, show, or album/artist/song.

### CODE REVIEW

**Review by m0ngr31 — APPROVED** [review]

**Comment by m0ngr31** [comment]
There is just a nagging conflict. I added a bunch of stuff I'd been working on last night so if you could fix the conflict, that'd be great.

**Comment by jingai** [comment]
I will fix the conflict this week.  Thanks for merging the other PRs :)

**Comment by m0ngr31** [comment]
Sorry it took me so long!

**Comment by jingai** [comment]
Rebased and resolved conflicts.

**Comment by m0ngr31** [comment]
I broke it again with your other PR!

**Comment by jingai** [comment]
lol give me 1 min and I'll fix

**Comment by jingai** [comment]
Rebased.  Sorry, should be clean now!

**Pull request merged**
