### PR TITLE
Add ListenToPlaylist Intent.

### PR DESCRIPTION
**Pull request by jingai**
Currently only supports music playlists.

This does require similar changes in your slot generator, as I changed the name of the MUSIC slot to MUSICARTISTS and added MUSICPLAYLISTS slot as well.

I'll submit another pull request for the changes to the slot generator.

### CODE REVIEW

**Comment by jingai** [comment]
If you don't intend to pull any of these, please just let me know so I can merge them all into master on my fork and continue on.

**Comment by 40wattrange** [comment]
If you do please let me know. I've liked your modifications and have ideas
for more. Would just switch my repo.

**Comment by m0ngr31** [comment]
I do plan on merging this in. Thank you for the PR. I have just been swamped between work and a client project. I really just need to spend some time and update the documentation and I'll me ready to merge my changes in as well.

**Comment by jingai** [comment]
No problem.  Was just making sure you were still there :)

**Comment by m0ngr31** [comment]
I'm hoping in the next week I'll be able to get all of your PRs merged + update docs + merge my local dev branch

**Review by m0ngr31 — APPROVED** [review]

**Comment by m0ngr31** [comment]
I merged this in, I'll need to update the docs now.

**Comment by jingai** [comment]
One comment: on "ListenToPlaylist listen to playlist {Playlist}" and all related, I added "ListenToPlaylist listen to {Playlist} playlist" as a variant because it seems my wife and I naturally speak the phrase differently.  I figured this might be an issue for others too.

I can make another PR for the variants, unless you're opposed to the idea.

edit: Added to https://github.com/m0ngr31/kodi-alexa/pull/12

**Pull request merged**
