### PR TITLE
Update python slot generator.

### PR DESCRIPTION
**Pull request by jingai**
To support MUSICARTISTS and MUSICPLAYLISTS.

### CODE REVIEW

**Comment by m0ngr31** [comment]
I actually just did this!

**Comment by m0ngr31** [comment]
Thanks for helping so much with this repo. I really appreciate it!

**Comment by jingai** [comment]
I have a fair bit more planned, so I'm just happy you're OK pulling changes :-P

**Comment by m0ngr31** [comment]
I definitely am!

**Pull request closed without merging**
