### PR TITLE
changes to EjectMedia utterances

### PR DESCRIPTION
**Pull request by digiltd**
added periods to cd dvd
included versions using "the" e.g. "eject the disc"

### CODE REVIEW

**Comment by jingai** [comment]
This isn't right.  The [docs](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/defining-the-voice-interface) say

> For better recognition, acronyms and other phrases involving spoken letters should either be all caps (“HD”) or separated by periods (“h.d.”). Using lowercase for initialisms may lead to unreliable recognition since the spoken form may not correctly be detected.

It's either lowercase with periods separating the letters (specifically, it doesn't say "also a space") or all capitals.

**Comment by digiltd** [comment]
Not sure what isn't right, you are describing exactly what I did.

I changed `eject cd` to `eject c. d.` 

You are confusing/referencing what the docs say about using acronyms in [Custom Slot values](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/defining-the-voice-interface#custom-slot-types) rather than Sample Utterances. 

The section [Custom Interaction Model Reference](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/alexa-skills-kit-interaction-model-reference#h3_intentref_rules) says the following about Sample Utterances and including a space:

> Acronyms and other phrases involving spoken letters should be separated by periods and spaces (“n. b. a.”, not “nba”).

**Comment by jingai** [comment]
Oh, yes, you are correct.  Odd that they'd have different rules for them.

**Comment by m0ngr31** [comment]
Can you make these changes on the `flask-ask` branch as well?

**Comment by jingai** [comment]
I had assumed we'd just rebase flask-ask onto current master.  I can do that, if you want me to?

**Comment by m0ngr31** [comment]
Either way is fine.

**Comment by jingai** [comment]
I can do it now, or later.  In general I rebase right before merging a branch.  Hadn't done it yet because these changes are pretty minor and shouldn't affect testing of the flask-ask branch in any meaningful way.

Plus I can't rebase without messing up your local branch, anyway.  Up to you if you think it's worth cherry-picking now, or just waiting for the merge.

**Pull request merged**
