### PR TITLE
Add Spanish

### PR DESCRIPTION
**Pull request by ruben0909**
Templates, Samples, utterances
Full translaction to spanish
Without accents and without ñ because of http://www.makermusings.com/amazon-echo-utterance-expander/ doesn´t allow it.

### CODE REVIEW

**Comment by ruben0909** [comment]
This resolve #275

**Comment by m0ngr31** [comment]
Looks good :)

**Comment by m0ngr31** [comment]
> Without accents and without ñ because of http://www.makermusings.com/amazon-echo-utterance-expander/ doesn´t allow it.

Maybe I need to build a new expander that supports that...

**Review by m0ngr31 — APPROVED** [review]

**Comment by ruben0909** [comment]
Thank you

**Pull request merged**
