### PR TITLE
send text to kodi, inc DE translation

### PR DESCRIPTION
**Pull request by digiltd**
needs the modified kodi-voice (https://github.com/digiltd/kodi-voice/tree/send-text)

you say "enter the text whatever you fancy"

she replies "I heard the text: whatever you fancy, is this correct?"

"yes" sends it

### CODE REVIEW

**Comment by jingai** [comment]
Have had some discussion on Slack that probably should go here.

Basically, the main concerns are:

* Things that aren't natural phrases, such as URLs, IP addresses, etc.  These come through Alexa in ways that we'd need to either accept will likely never be what the user intended, or would need translation in the skill.  This is a complex problem since we'd need to identify the user's intention.  Further, the problem is compounded by the fact that we also support German (and I'm assuming other languages in the future)

* Collisions with other utterances, since it's more likely that the slot value here might sound similar to one of our other utterances.  We were able to get her to fire the wrong Intent by asking for a URL and oddly, the phrase, `i have got a lovely bunch of coconuts`.  I'm inclined to think we probably will find more, and testing for that is difficult.

**Comment by jingai** [comment]
I've put up PR https://github.com/digiltd/kodi-alexa/pull/1 for changes that I think should go into this as well.

**Comment by mcl22** [comment]
Here are the translations (I found in the code):

EnterText schreibe (/den) Text {Phrase}
EnterText gib (den/folgenden) Text ein {Phrase}  

Ich habe folgenden Text gehört:
{{ heard_text }}
Ist das korrekt?
 
Du möchtest dass ich folgenden Text eingebe:
{{ heard_text }}
Richtig?

**Comment by digiltd** [comment]
@mcl22 not sure it is going in or not, but can you also do your magic for:

try_enter_text_again: "Try again, say: Enter Text. followed by the text you want to enter."

**Comment by mcl22** [comment]
Abracadabra ... 
try_enter_text_again: "Versuche es erneut, sage: gib Text ein, gefolgt von dem Text, den du eingeben möchtest."

**Comment by digiltd** [comment]
Thanks, I have updated it at my end, the try_enter_text_again question is a bit of a mouthful in both languages. Ideally she would ask "you said blah blah, if this correct?" and if you said "no" she would just say "say it again". But when she starts listening again, you can trigger any intent, so it is important to make sure the users says the whole phrase.

**Pull request closed without merging**
