### PR TITLE
Add support for music genres.

### PR DESCRIPTION
**Pull request by jingai**
Adds support for requesting music by genre.  With this, you can say things like:

```
play Rock music
listen to Classical genre
shuffle Rap songs
listen to Christmas music by Scott Weiland
```

I've tested it some, but it is definitely possible the utterances might clash, so I wanted to get this up here as a PR for others to play with.

Obviously, the web slot generator needs to be updated to output MUSICGENRES as well.

Addresses Issue #107.

### CODE REVIEW

**Comment by jingai** [comment]
@mcl22 suggested I change the German utterances for ListenToArtist to:

`ListenToArtist spiel(/e) (/{MusicGenre}) (Musik/Songs) von (/dem Artist/dem Künstler/der Band/dem Interpreten) {Artist}`

Minor change, but I'm wondering if no one would really ever use `Gruppe` or `Komponist`?

**Comment by jingai** [comment]
@mcl22 and @ausweider please check over the German translations and make sure they're working for you.

**Comment by danielmasur** [comment]
Looks good to me.
Side note: the german utterances are in dire need of a rewrite in the future though.

**Comment by jingai** [comment]
Ok, this just needs MUSICGENRES added to the web slot generator then.  Ping @m0ngr31

**Pull request closed without merging**
